image: debian:trixie

stages:
  - prepare
  - test

.build-setup: &build-setup
  before_get_sources:
    - apt-get -yq update > /dev/null && apt-get -yq upgrade
    - apt-get -yq install python3 make build-essential autoconf flex bison git ccache help2man curl cmake gzip file grep gawk lld clang libffi-dev libfl-dev libreadline-dev pkg-config tcl-dev zlib1g-dev graphviz xdot 7zip

.veer-setup: &veer-setup
  before_get_sources:
    - apt-get update &> /dev/null
    - apt-get -y --no-install-recommends install
      autoconf bc bison build-essential ca-certificates ccache clang
      cmake flex gdb git gtkwave help2man libfl2 libfl-dev libclang-rt-18-dev
      libgoogle-perftools-dev libsystemc libsystemc-dev perl wget python3-distro
      z3 zlib1g zlib1g-dev time libssl-dev libbz2-dev libreadline-dev libsqlite3-dev
      curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev
      liblzma-dev python3-openssl python3-venv mold python3-full python3-yaml
      python3 python3-dev python3-pip gfortran libopenblas-dev pkg-config
      libbit-vector-perl liblz4-dev 7zip
  before_script:
    - cd third_party/Cores-VeeR-EL2
    - git submodule update --init --recursive .
    - git apply ../../test/veer/veer_synth_and_sim_prep.patch
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - export RV_ROOT=$(pwd)
    - $RV_ROOT/configs/veer.config -set=lockstep_enable=1 -set=lockstep_delay=2 -set=lockstep_regfile_enable=0 -snapshot=dual

prepare-verilator:
  <<: *build-setup
  stage: prepare
  variables:
    VERILATOR_ROOT: /ci/verilator
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16000
    CCACHE_DIR: .ccache
  cache:
    paths:
     - $CCACHE_DIR
  script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@${VERILATOR_URL}" -b master "$VERILATOR_ROOT"
    - cd verilator
    - git show -s
    - autoconf
    - ./configure --prefix=`pwd`
    - make -j `nproc`
  artifacts:
    when: always
    paths:
      - verilator
    expire_in: 8 hours

prepare-yosys:
  <<: *build-setup
  stage: prepare
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16000
    CCACHE_DIR: .ccache
  cache:
    paths:
     - $CCACHE_DIR
  script:
    - cd third_party/yosys
    - git submodule update --init --recursive .
    - make config-gcc
    - make -j `nproc` CXX="ccache g++"
    - make install
    - cd ../
    - export PATH=$(pwd)/yosys:$PATH
    - export YOSYS_PREFIX=$(pwd)/yosys/
    - ls -l $YOSYS_PREFIX
    - cd yosys-slang
    - git submodule update --init --recursive .
    - make -j $(nproc) CXX="ccache g++" install
    - mkdir ../yosys/share/plugins
    - cp build/slang.so ../yosys/share/plugins
  artifacts:
    when: always
    paths:
      - third_party/yosys
    expire_in: 8 hours

prepare-liberty:
  <<: *build-setup
  stage: prepare
  variables:
    SCALENODE_RAM: 4000
  script:
    - git submodule update --init --recursive third_party/asap7
  artifacts:
    when: always
    paths:
      - third_party/asap7/LIB/NLDM/asap7sc7p5t_*_RVT_TT_nldm_*.lib.7z
    expire_in: 8 hours

check-formatting:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000 # the only way to force generation of slang headers is to build slang_slang, which fails on 4000 RAM
  before_script:
    - apt-get update && apt-get install -y clang-format-19 clang-tidy-19 cmake build-essential
    - cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build build --target slang_slang -j $(nproc)
  script:
    - echo "Checking formatting..."
    - find ./src -regextype posix-egrep -regex '.*(\.cpp|\.h)' -print0 | xargs -0 clang-format-19 --dry-run --Werror
    - echo "Checking linting..."
    - run-clang-tidy-19 -p build "^$(pwd)/src/.*(\.cpp|\.h)$" -header-filter="^$(pwd)/src/.*" -warnings-as-errors='*'

run-example:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
  script:
    - export PATH=$(pwd)/third_party/yosys:$PATH
    - cd example
    - bash run.sh
  artifacts:
    when: always
    paths:
      - example/obj_dir

run-self-tests:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - set -o pipefail
    - export PATH=$(pwd)/third_party/yosys:$PATH
    - cmake -B build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build -j $(nproc) 2>&1 | tee build/Testing/Temporary/cmake-build.log
    - ctest --test-dir build --output-on-failure --tests-regex 'unit|integration'
  artifacts:
    when: always
    paths:
      - build/
    expire_in: 8 hours

.run-end-to-end-tests:
  <<: *veer-setup
  stage: test
  variables:
    SCALENODE_RAM: 16000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - set -o pipefail
    - export PATH=$(pwd)/third_party/yosys:$PATH
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@${SYNTH_CACHE_URL}" --depth 1 -b synth-cache synth_cache
    - cmake -B build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DVEER_JSON_NETLIST_CACHE_PATH=/ci/synth_cache/veer_post_synth.json -DVEER_VERILOG_NETLIST_CACHE_PATH=/ci/synth_cache/veer_post_synth.v
    - cmake --build build -j $(nproc) 2>&1 | tee build/cmake-build.log
    - ctest --test-dir build --output-on-failure --tests-regex e2e.${CI_PARALLEL_NAME}
  artifacts:
    when: always
    paths:
      - build
    expire_in: 8 hours

Run End to End tests:
  extends: .run-end-to-end-tests
  parallel:
    - worker
    - veer

run-parser-tests:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-liberty
  before_script:
    - git clone --depth 1 https://github.com/The-OpenROAD-Project/OpenROAD.git /ci/OpenROAD
  script:
    - ./build.sh
    - src/FaultGenerator/test/testParser.sh /ci/OpenROAD/test build/src/FaultGenerator/test/LibertyParserBin
    - src/FaultGenerator/test/testParser.sh /ci/third_party/asap7 build/src/FaultGenerator/test/LibertyParserBin

run-veer-sanity-check:
  <<: *veer-setup
  stage: test
  variables:
    VERILATOR_ROOT: /ci/verilator
    SCALENODE_RAM: 16000
    PYTHONUNBUFFERED: "TRUE"
  script:
    - export PATH="$(pwd)/verilator/bin:$PATH"
    - cd third_party/Cores-VeeR-EL2
    - export RV_ROOT=$(pwd)
    - source .venv/bin/activate
    - VERILATOR_EXTRA_ARGS="--vpi" make -f $RV_ROOT/tools/Makefile verilator snapshot=dual

run-veer-synth:
  <<: *veer-setup
  stage: test
  when: manual
  variables:
    SCALENODE_RAM: 16000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - set -o pipefail
    - export PATH=$(pwd)/third_party/yosys:$PATH
    - cmake -B build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build -j $(nproc) --target=fi_e2e_veer_basic_netlist 2>&1 | tee build/cmake-build.log
  artifacts:
    when: always
    paths:
      - build
