image: debian:trixie

variables:
  CXX: 'g++-14'
  CC: 'gcc-14'

stages:
  - prepare
  - test

.build-setup: &build-setup
  before_script:
    - ci/install-packages.sh

.veer-setup: &veer-setup
  before_get_sources:
    - apt-get update &> /dev/null
    - apt-get -y --no-install-recommends install
      autoconf bc bison build-essential ca-certificates ccache gcc
      cmake flex gdb git gtkwave help2man libfl2 libfl-dev libclang-rt-19-dev
      libgoogle-perftools-dev libsystemc libsystemc-dev perl wget python3-distro
      z3 zlib1g zlib1g-dev time libssl-dev libbz2-dev libreadline-dev libsqlite3-dev
      curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev
      liblzma-dev python3-openssl python3-venv mold python3-full python3-yaml
      python3 python3-dev python3-pip gfortran libopenblas-dev pkg-config
      libbit-vector-perl liblz4-dev 7zip
  before_script:
    - cd third_party/Cores-VeeR-EL2
    - git submodule update --init --recursive .
    - git apply ../../test/veer/veer_synth_and_sim_prep.patch
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - export RV_ROOT=$(pwd)
    - $RV_ROOT/configs/veer.config -set=lockstep_enable=1 -set=lockstep_delay=2 -set=lockstep_regfile_enable=0 -snapshot=dual

prepare-verilator:
  <<: *build-setup
  stage: prepare
  variables:
    VERILATOR_ROOT: /ci/verilator
    VERILATOR_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@${VERILATOR_URL}
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16000
    CCACHE_DIR: .ccache
  cache:
    paths:
     - $CCACHE_DIR
  script:
    - ci/build-verilator.sh
  artifacts:
    when: always
    paths:
      - verilator
    expire_in: 8 hours

prepare-yosys:
  <<: *build-setup
  stage: prepare
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16000
    CCACHE_DIR: .ccache
  cache:
    paths:
     - $CCACHE_DIR
  script:
    - ci/build-yosys.sh
  artifacts:
    when: always
    paths:
      - third_party/yosys
    expire_in: 8 hours

prepare-liberty:
  <<: *build-setup
  stage: prepare
  variables:
    SCALENODE_RAM: 4000
  script:
    - git submodule update --init --recursive third_party/asap7
  artifacts:
    when: always
    paths:
      - third_party/asap7/LIB/NLDM/asap7sc7p5t_*_RVT_TT_nldm_*.lib.7z
    expire_in: 8 hours

check-formatting:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 4000
  script:
    - ci/check-formatting.sh

run-example:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
  script:
    - ci/run-example.sh
  artifacts:
    when: always
    paths:
      - example/obj_dir

run-self-tests:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - ci/run-self-tests.sh
  artifacts:
    when: always
    paths:
      - build/
    expire_in: 8 hours

.run-end-to-end-tests:
  <<: *veer-setup
  stage: test
  variables:
    SCALENODE_RAM: 16000
    VERILATOR_ROOT: /ci/verilator
    VEER_JSON_NETLIST_CACHE_PATH: /ci/synth_cache/veer_post_synth.json
    VEER_VERILOG_NETLIST_CACHE_PATH: /ci/synth_cache/veer_post_synth.v
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@${SYNTH_CACHE_URL}" --depth 1 -b synth-cache synth_cache
    - ci/run-e2e-tests.sh "${CI_PARALLEL_NAME}"
  artifacts:
    when: always
    paths:
      - build
    expire_in: 8 hours

Run End to End tests:
  extends: .run-end-to-end-tests
  parallel:
    - worker
    - veer
    - coverage

run-parser-tests:
  <<: *build-setup
  stage: test
  variables:
    SCALENODE_RAM: 8000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-liberty
  script:
    - git clone --depth 1 https://github.com/The-OpenROAD-Project/OpenROAD.git /ci/OpenROAD
    - ci/run-parser-tests.sh /ci/OpenROAD/test /ci/third_party/asap7

run-veer-sanity-check:
  <<: *veer-setup
  stage: test
  variables:
    VERILATOR_ROOT: /ci/verilator
    SCALENODE_RAM: 16000
    PYTHONUNBUFFERED: "TRUE"
  script:
    - export PATH="$(pwd)/verilator/bin:$PATH"
    - cd third_party/Cores-VeeR-EL2
    - export RV_ROOT=$(pwd)
    - source .venv/bin/activate
    - VERILATOR_EXTRA_ARGS="--vpi" make -f $RV_ROOT/tools/Makefile verilator snapshot=dual

run-veer-synth:
  <<: *veer-setup
  stage: test
  when: manual
  variables:
    SCALENODE_RAM: 16000
    VERILATOR_ROOT: /ci/verilator
  dependencies:
    - prepare-verilator
    - prepare-yosys
    - prepare-liberty
  script:
    - set -o pipefail
    - export PATH=$(pwd)/third_party/yosys/build:$PATH
    - cmake -B build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DFI_E2E_GENERATOR_EXTRA_DEBUG=3
    - cmake --build build -j $(nproc) --target=fi_e2e_veer_basic_netlist 2>&1 | tee build/cmake-build.log
  artifacts:
    when: always
    paths:
      - build
