// Copyright 2026 Antmicro <antmicro.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#include "GlobalOpts.h"

#include "FaultStrategy/Factory.h"
#include "LogUtils.h"
#include "UnitUtils.h"

#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
#include <absl/flags/usage.h>
#include <absl/flags/usage_config.h>
#include <nlohmann/json.hpp>

#include <cmath>
#include <fstream>

ABSL_FLAG(
    std::string,
    sig_path_prefix,
    "",
    "Hierarchical path to the top module's parent (e.g. `top`). Empty (default) if the top module "
    "is the design top."
);
ABSL_FLAG(
    std::string,
    top_port_path_prefix,
    "TOP",
    "Prefix for top design port paths. Useful when simulators define custom prefix path for "
    "top level ports, e.g. `TOP` for Verilator. Only applicable when `sig_prefix_path` is empty."
);
ABSL_FLAG(std::string, top_module, "", "Top module name.");
ABSL_FLAG(std::string, top_instance, "", "Top module instance name.");
ABSL_FLAG(std::string, netlist_path, "", "Path to the netlist generated by Yosys.");
ABSL_FLAG(
    std::string,
    placement_info_path,
    "",
    "Path to CSV containing cell placement information."
);
ABSL_FLAG(
    std::optional<std::string>,
    simulation_time,
    std::nullopt,
    "Total duration of the simulation. When not specified, defaults to 1000s."
);
ABSL_FLAG(bool, collect_wires, true, "Whether wires are included in generated campaigns.");
ABSL_FLAG(
    std::string,
    wire_attribute,
    "hdlname",
    "Attribute required on collected non-port wires. An empty value collects all wires."
);
ABSL_FLAG(
    bool,
    deduplicate_wires,
    true,
    "Exclude wires already represented by flip-flops. Relies on Yosys assigning auto-generated "
    "names based on the wires they drive. See Yosys' documentation of `rename -wire` command."
);
ABSL_FLAG(
    std::vector<std::string>,
    clk_names,
    {},
    "Comma-separated wire names to exclude as clocks. Will exclude signals where clock name "
    "matches last signal path part after the `.` hierarchy separator."
);
constexpr unit::SIM_TIME simulation_time_default = 1000 * unit::s;
ABSL_FLAG(
    std::optional<std::uint64_t>,
    num_of_events,
    std::nullopt,
    "Number of generated single-event effects. Setting it to [0] disables this limit."
);
constexpr std::uint64_t num_of_events_default = 0;
ABSL_FLAG(
    std::optional<std::uint32_t>,
    seed,
    std::nullopt,
    "Random seed. When not specified, defaults to '42'."
);
constexpr std::uint64_t seed_default = 42;
ABSL_FLAG(
    std::optional<std::string>,
    fault_campaign_out,
    std::nullopt,
    "Path for generated fault campaign file. When not specified, defaults to "
    "'fault_campaign_out.csv'."
);
constexpr std::string_view fault_campaign_out_file_default = "fault_campaign_out.csv";
constexpr std::string_view fault_campaign_out_directory_default = "fault_campaign_out";
ABSL_FLAG(
    std::optional<float>,
    latchup_probability,
    std::nullopt,
    "Percentage probability of single event latchup (SEL) as compared to single event transients "
    "(SET), "
    "defaults to 0%."
);
constexpr float latchup_probability_default = 0;
ABSL_FLAG(
    std::string,
    config_file,
    "",
    "Path to configuration file. When this flag is provided, most flags are ignored."
);
ABSL_FLAG(
    std::uint64_t,
    campaign_number,
    1,
    "Number of campaigns to generate. If number is greater than 1, `--fault_campaign_out` is "
    "treated as a directory"
);
ABSL_FLAG(
    std::optional<std::uint32_t>,
    thread_number,
    std::nullopt,
    "Number of threads to use. When not provided, defaults to '1'"
);
constexpr std::uint32_t thread_number_default = 1;
ABSL_FLAG(
    std::vector<std::string>,
    liberty_paths,
    {},
    "List of comma separated paths to liberty files."
);
ABSL_FLAG(
    std::string,
    liberty_area_scale,
    "",
    "Indicator as to how to treat sizes in liberty files. If '0.5mm2' is given,"
    " cell with area=1, will be treated as area=0.5mm2.\n"
    "Available units are: m2, cm2, mm2, um2, nm2."
    "When not provided, defaults to '1um2'"
);
constexpr unit::AREA default_liberty_area_scale = 1 * unit::um2;
ABSL_FLAG(
    std::string,
    cell_area_json_path,
    "",
    "Alternative way to provide information available via liberty."
);

ABSL_FLAG(
    std::optional<std::string>,
    vlt_config,
    std::nullopt,
    "File path of where to print config of which signals verilator should expose. In absence of "
    "this flag, config isn't written at all."
);
ABSL_FLAG(
    std::string,
    mbu_radius,
    "",
    "Radius containing 95% of sampled secondary MBU points, measured from the primary cell "
    "center (e.g. 2.5um). Larger radii spread hits farther away; this is not a hard cutoff. "
    "Must be finite and positive. Requires '--placement_info_path'."
);

namespace {

std::uint32_t clampThreadNumber(std::uint32_t thread_number) {
    return std::max(1u, thread_number);
}

unit::SIM_TIME getSimulationTime(std::string_view sim_time_str) {
    if (sim_time_str.empty()) {
        return simulation_time_default;
    }

    auto parsed = unit::parseQuantity(sim_time_str);
    if (!parsed) {
        LOG(WARNING) << "Failed to parse simulation time. Using default value: "
                     << std::format("{}", simulation_time_default);
        return simulation_time_default;
    }

    auto [value, unit] = *parsed;
    if (auto result = unit::normalizeSimTime(value, unit)) {
        return *result;
    }
    LOG(WARNING) << "Unrecognized simulation time unit: '" << unit
                 << "'. Using default value: " << std::format("{}", simulation_time_default);
    return simulation_time_default;
}

unit::AREA getLibertyAreaScale(std::string_view area_scale_str) {
    if (area_scale_str.empty()) {
        return default_liberty_area_scale;
    }

    auto parsed = unit::parseQuantity(area_scale_str);
    if (!parsed) {
        LOG(WARNING) << "Failed to parse liberty area scale. Using default value: "
                     << std::format("{}", default_liberty_area_scale);
        return default_liberty_area_scale;
    }

    auto [value, unit] = *parsed;
    if (auto result = unit::normalizeArea(value, unit)) {
        return *result;
    }
    LOG(WARNING) << "Unrecognized liberty area scale unit: '" << unit
                 << "'. Using default value: " << std::format("{}", default_liberty_area_scale);
    return default_liberty_area_scale;
}

std::optional<unit::DIST> getMBURadius(std::string_view mbu_radius_str) {
    if (mbu_radius_str.empty()) {
        return std::nullopt;
    }

    auto parsed = unit::parseQuantity(mbu_radius_str);
    if (!parsed) {
        LOG(WARNING) << "Failed to parse MBU radius. Disabling the feature.";
        return std::nullopt;
    }

    auto [value, unit] = *parsed;
    if (auto result = unit::normalizeDist(value, unit)) {
        const double radius = result->numerical_value_in(unit::DIST::unit);
        if (std::isfinite(radius) && radius > 0) {
            return result;
        }
        LOG(WARNING) << "MBU radius must be finite and positive. Disabling the feature.";
        return std::nullopt;
    }
    LOG(WARNING) << "Unrecognized MBU radius unit. Disabling the feature.";
    return std::nullopt;
}

void configureUsageMessage() {
    absl::SetProgramUsageMessage(
        "Generate fault-injection campaigns from a synthesized netlist.\n"
        "Settings can be provided as command-line flags or loaded from JSON with --config_file."
    );
    absl::FlagsUsageConfig usage_config;

    // NOTE: The magic below is to avoid absl printing the exact source file origin
    // of flags, and instead say something more pleasant
    usage_config.normalize_filename = [](absl::string_view filename) {
        if (filename.ends_with("GlobalOpts.cpp")) {
            return "faultergeist-gen";
        }
        return "";
    };
    usage_config.contains_help_flags = [](absl::string_view filename) {
        return filename == "faultergeist-gen";
    };
    usage_config.contains_helpshort_flags = [](absl::string_view filename) {
        return filename == "faultergeist-gen";
    };
    absl::SetFlagsUsageConfig(std::move(usage_config));
}

};  // namespace

void from_json(const nlohmann::json& json, FaultStrategy::Config& config) {
    if (const auto num_of_events = absl::GetFlag(FLAGS_num_of_events)) {
        VLOG(2) << "Config.num_of_events set from flag";
        config.num_of_events = *num_of_events;
    } else {
        VLOG(2) << "Config.num_of_events set from json/default";
        config.num_of_events = json.value("num_of_events", num_of_events_default);
    }

    if (const auto seed = absl::GetFlag(FLAGS_seed)) {
        VLOG(2) << "Config.seed set from flag";
        config.seed = *seed;
    } else {
        VLOG(2) << "Config.seed set from json/default";
        config.seed = json.value("seed", seed_default);
    }

    if (const auto latchup_probability = absl::GetFlag(FLAGS_latchup_probability)) {
        VLOG(2) << "Config.latchup_probability set from flag";
        config.latchup_probability = *latchup_probability * unit::PERCENT::unit;
    } else {
        VLOG(2) << "Config.latchup_probability set from json/default";
        config.latchup_probability =
            json.value("latchup_probability", latchup_probability_default) * unit::PERCENT::unit;
    }

    config.transient_probability = 100 * unit::PERCENT::unit - config.latchup_probability;

    if (const auto simulation_time = absl::GetFlag(FLAGS_simulation_time)) {
        VLOG(2) << "Config.simulation_time set from flag";
        config.simulation_time = getSimulationTime(*simulation_time);
    } else {
        VLOG(2) << "Config.simulation_time set from json/default";
        config.simulation_time = getSimulationTime(json.value("simulation_time", ""));
    }

    if (const auto thread_number = absl::GetFlag(FLAGS_thread_number)) {
        VLOG(2) << "GlobalOpts.thread_number set from flag";
        config.thread_number = clampThreadNumber(*thread_number);
    } else {
        VLOG(2) << "GlobalOpts.thread_number set from json/default";
        config.thread_number =
            clampThreadNumber(json.value("thread_number", thread_number_default));
    }

    VLOG(3) << "Config" << config;
}

void from_json(const nlohmann::json& json, GlobalOpts& opts) {
    const auto& model = json.at("model");
    const auto& params = json["params"];

#define GET_OR_DEFAULT(name) \
    do { \
        const bool from_config = params.contains(#name); \
        opts.name = \
            params.value(#name, absl::GetFlagReflectionHandle(FLAGS_##name).DefaultValue()); \
        VLOG(2) << "GlobalOpts." #name " = '" << opts.name << "' (" \
                << (from_config ? "config" : "default") << ")"; \
    } while (false)
    GET_OR_DEFAULT(sig_path_prefix);
    GET_OR_DEFAULT(top_port_path_prefix);
    GET_OR_DEFAULT(top_module);
    GET_OR_DEFAULT(top_instance);
    GET_OR_DEFAULT(netlist_path);
    GET_OR_DEFAULT(cell_area_json_path);
    GET_OR_DEFAULT(placement_info_path);
    GET_OR_DEFAULT(wire_attribute);
#undef GET_OR_DEFAULT
    opts.collect_wires = params.value("collect_wires", true);
    opts.deduplicate_wires = params.value("deduplicate_wires", true);
    opts.clk_names = params.value<std::vector<std::string>>("clk_names", {});
    if (params.contains("vlt_config")) {
        VLOG(2) << "GlobalOpts.vlt_config set from json";
        opts.vlt_config = params["vlt_config"].get<std::string>();
    } else if (absl::GetFlag(FLAGS_vlt_config)) {
        VLOG(2) << "GlobalOpts.vlt_config set from flag";
        opts.vlt_config = absl::GetFlag(FLAGS_vlt_config);
    }
    opts.campaign_number = params.value(
        "campaign_number",
        std::stoi(absl::GetFlagReflectionHandle(FLAGS_campaign_number).DefaultValue())
    );
    opts.liberty_paths = params.value<std::vector<std::string>>("liberty_paths", {});

    FaultStrategy::Config config = params.get<FaultStrategy::Config>();
    opts.strategy = FaultStrategyFactory::buildFromJson(config, model);

    if (absl::GetFlag(FLAGS_fault_campaign_out)) {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from flag";
        opts.fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
    } else if (params.contains("fault_campaign_out")) {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from json";
        opts.fault_campaign_out = params["fault_campaign_out"].get<std::string>();
    } else {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from default";
        if (opts.campaign_number == 1) {
            opts.fault_campaign_out = fault_campaign_out_file_default;
        } else {
            opts.fault_campaign_out = fault_campaign_out_directory_default;
        }
    }

    if (!absl::GetFlag(FLAGS_liberty_area_scale).empty()) {
        VLOG(2) << "GlobalOpts.liberty_area_scale set from flag";
        opts.liberty_area_scale = getLibertyAreaScale(absl::GetFlag(FLAGS_liberty_area_scale));
    } else if (params.contains("liberty_area_scale")) {
        VLOG(2) << "GlobalOpts.liberty_area_scale set from json";
        opts.liberty_area_scale =
            getLibertyAreaScale(params["liberty_area_scale"].get<std::string>());
    } else {
        opts.liberty_area_scale = default_liberty_area_scale;
    }

    if (!absl::GetFlag(FLAGS_mbu_radius).empty()) {
        VLOG(2) << "GlobalOpts.mbu_radius set from flag";
        opts.mbu_radius = getMBURadius(absl::GetFlag(FLAGS_mbu_radius));
    } else {
        VLOG(2) << "GlobalOpts.mbu_radius set from json/default";
        opts.mbu_radius = getMBURadius(params.value("mbu_radius", ""));
    }
}

GlobalOpts GlobalOpts::parseCmdArgs(int argc, char** argv) {
    configureUsageMessage();
    absl::ParseCommandLine(argc, argv);
    LogInitialize();

    std::string config_filepath = absl::GetFlag(FLAGS_config_file);
    if (config_filepath.empty()) {
        FaultStrategy::Config config = {
            .num_of_events = absl::GetFlag(FLAGS_num_of_events).value_or(num_of_events_default),
            .seed = absl::GetFlag(FLAGS_seed).value_or(seed_default),
            .simulation_time = getSimulationTime(absl::GetFlag(FLAGS_simulation_time).value_or("")),
            .thread_number =
                clampThreadNumber(absl::GetFlag(FLAGS_thread_number).value_or(thread_number_default)
                ),
            .latchup_probability = latchup_probability_default * unit::PERCENT::unit,
            .transient_probability = (100 - latchup_probability_default) * unit::PERCENT::unit
        };

        std::uint64_t campaign_number = absl::GetFlag(FLAGS_campaign_number);
        std::string fault_campaign_out;
        if (absl::GetFlag(FLAGS_fault_campaign_out)) {
            VLOG(2) << "GlobalOpts.fault_campaign_out set from flag";
            fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
        } else {
            VLOG(2) << "GlobalOpts.fault_campaign_out set from default";
            if (campaign_number == 1) {
                fault_campaign_out = fault_campaign_out_file_default;
            } else {
                fault_campaign_out = fault_campaign_out_directory_default;
            }
        }
        unit::AREA liberty_area_scale =
            getLibertyAreaScale(absl::GetFlag(FLAGS_liberty_area_scale));

        // TODO Check that all required flags were passed
        return {
            .sig_path_prefix = absl::GetFlag(FLAGS_sig_path_prefix),
            .top_port_path_prefix = absl::GetFlag(FLAGS_top_port_path_prefix),
            .top_module = absl::GetFlag(FLAGS_top_module),
            .top_instance = absl::GetFlag(FLAGS_top_instance),
            .netlist_path = absl::GetFlag(FLAGS_netlist_path),
            .placement_info_path = absl::GetFlag(FLAGS_placement_info_path),
            .fault_campaign_out = fault_campaign_out,
            .campaign_number = campaign_number,
            .strategy = FaultStrategyFactory::defaultStrategy(config),
            .liberty_paths = absl::GetFlag(FLAGS_liberty_paths),
            .liberty_area_scale = liberty_area_scale,
            .vlt_config = absl::GetFlag(FLAGS_vlt_config),
            .cell_area_json_path = absl::GetFlag(FLAGS_cell_area_json_path),
            .mbu_radius = getMBURadius(absl::GetFlag(FLAGS_mbu_radius)),
            .collect_wires = absl::GetFlag(FLAGS_collect_wires),
            .wire_attribute = absl::GetFlag(FLAGS_wire_attribute),
            .deduplicate_wires = absl::GetFlag(FLAGS_deduplicate_wires),
            .clk_names = absl::GetFlag(FLAGS_clk_names)
        };
    } else {
        try {
            std::ifstream config_file{config_filepath};
            SEE_PCHECK(config_file) << "Failed to open '" << config_filepath << "'";
            const auto config_json = nlohmann::json::parse(config_file);

            return config_json.get<GlobalOpts>();
        } catch (std::exception& error) {
            LOG(INFO) << "Json config parsing error: " << error.what() << "\n";
            SEE_CHECK(false) << "Ill formed config file '" << config_filepath << "'";
        }
    }
}
