// Copyright 2026 Antmicro <antmicro.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#include "GlobalOpts.h"

#include "FaultStrategy/Factory.h"
#include "LogUtils.h"
#include "UnitUtils.h"

#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
#include <nlohmann/json.hpp>

#include <fstream>

ABSL_FLAG(std::string, sig_path_prefix, "", "Prefix for signal paths, i.e. `top`.");
ABSL_FLAG(std::string, top_module, "", "Name of the top module.");
ABSL_FLAG(std::string, top_instance, "", "Name of the top module instance.");
ABSL_FLAG(std::string, netlist_path, "", "Path to the netlist generated by Yosys.");
ABSL_FLAG(
    std::optional<std::string>,
    simulation_time,
    std::nullopt,
    "Total duration of the simulation."
);
const unit::SIM_TIME simulation_time_default = 1000 * unit::s;
ABSL_FLAG(
    std::optional<std::uint64_t>,
    num_of_events,
    std::nullopt,
    "Number of generated single-event effects. Setting it to [0] disables this limit."
);
const std::uint64_t num_of_events_default = 0;
ABSL_FLAG(std::optional<std::uint32_t>, seed, std::nullopt, "Random seed.");
const std::uint64_t seed_default = 42;
ABSL_FLAG(
    std::optional<std::string>,
    fault_campaign_out,
    std::nullopt,
    "Path for generated fault campaign file."
);
ABSL_FLAG(
    std::string,
    config_file,
    "",
    "Path to configuration file. If this flag is present, all others are ignored."
);
ABSL_FLAG(
    std::uint64_t,
    campaign_number,
    1,
    "Number of campaigns to generate. If number is greater than 1, `--fault_campaign_out` is "
    "treated as a directory"
);
ABSL_FLAG(std::optional<std::uint32_t>, thread_number, std::nullopt, "Number of threads to use.");
const std::uint32_t thread_number_default = 1;
const char* fault_campaign_out_file_defualt = "fault_campaign_out.csv";
const char* fault_campaign_out_directory_defualt = "fault_campaign_out";
ABSL_FLAG(
    std::vector<std::string>,
    liberty_paths,
    {},
    "List of comma separated paths to liberty files."
);
ABSL_FLAG(
    std::string,
    liberty_area_scale,
    "",
    "Indicator as to how to treat sizes in liberty files. If '0.5mm2' is given,"
    " cell with area=1, will be treated as area=0.5mm2.\n"
    "Available units are: m2, cm2, mm2, um2, nm2."
);
const unit::AREA default_liberty_area_scale = 1 * unit::um2;

namespace {

std::uint32_t clampThreadNumber(std::uint32_t thread_number) {
    return std::max(1u, thread_number);
}

unit::SIM_TIME parse_simulation_time(std::string_view sim_time_str) {
    if (sim_time_str.empty()) {
        return simulation_time_default;
    }

    auto parsed = unit::parseTime(sim_time_str);
    if (!parsed) {
        LOG(WARNING) << "Failed to parse simulation time. Using default value: "
                     << std::format("{}", simulation_time_default);
        return simulation_time_default;
    }

    auto [value, unit] = *parsed;
    if (auto result = unit::normalizeSimTime(value, unit)) {
        return *result;
    }
    LOG(WARNING) << "Unrecognized simulation time unit: '" << unit
                 << "'. Using default value: " << std::format("{}", simulation_time_default);
    return simulation_time_default;
}

static std::optional<unit::AREA> normalizeArea(double value, std::string_view unit) {
    if (unit == "m2") {
        return value * unit::m2;
    }
    if (unit == "cm2") {
        return value * unit::cm2;
    }
    if (unit == "mm2") {
        return value * unit::mm2;
    }
    if (unit == "um2") {
        return value * unit::um2;
    }
    if (unit == "nm2") {
        return value * unit::nm2;
    }
    return std::nullopt;
}

unit::AREA getLibertyAreaScale(std::string_view area_scale_str) {
    if (area_scale_str.empty()) {
        return default_liberty_area_scale;
    }

    auto parsed = unit::parseTime(area_scale_str);
    if (!parsed) {
        LOG(WARNING) << "Failed to parse liberty area scale. Using default value: "
                     << std::format("{}", default_liberty_area_scale);
        return default_liberty_area_scale;
    }

    auto [value, unit] = *parsed;
    if (auto result = normalizeArea(value, unit)) {
        return *result;
    }
    LOG(WARNING) << "Unrecognized liberty area scale unit: '" << unit
                 << "'. Using default value: " << std::format("{}", default_liberty_area_scale);
    return default_liberty_area_scale;
}

};  // namespace

void from_json(const nlohmann::json& json, FaultStrategy::Config& config) {
    if (absl::GetFlag(FLAGS_num_of_events)) {
        VLOG(2) << "Config.num_of_events set from flag";
        config.num_of_events = absl::GetFlag(FLAGS_num_of_events).value();
    } else {
        VLOG(2) << "Config.num_of_events set from json/default";
        config.num_of_events = json.value("num_of_events", num_of_events_default);
    }

    if (absl::GetFlag(FLAGS_seed)) {
        VLOG(2) << "Config.seed set from flag";
        config.seed = absl::GetFlag(FLAGS_seed).value();
    } else {
        VLOG(2) << "Config.seed set from json/default";
        config.seed = json.value("seed", seed_default);
    }

    if (absl::GetFlag(FLAGS_simulation_time)) {
        VLOG(2) << "Config.simulation_time set from flag";
        config.simulation_time =
            parse_simulation_time(absl::GetFlag(FLAGS_simulation_time).value());
    } else {
        VLOG(2) << "Config.simulation_time set from json/default";
        config.simulation_time = parse_simulation_time(json.value("simulation_time", ""));
    }

    if (absl::GetFlag(FLAGS_thread_number)) {
        VLOG(2) << "GlobalOpts.thread_number set from flag";
        config.thread_number = clampThreadNumber(absl::GetFlag(FLAGS_thread_number).value());
    } else {
        VLOG(2) << "GlobalOpts.thread_number set from json/default";
        config.thread_number =
            clampThreadNumber(json.value("thread_number", thread_number_default));
    }

    VLOG(3) << "Config" << config;
}

void from_json(const nlohmann::json& json, GlobalOpts& opts) {
    const auto& model = json.at("model");
    const auto& params = json["params"];

#define GET_OR_DEFAULT(name) \
    opts.name = params.value(#name, absl::GetFlagReflectionHandle(FLAGS_##name).DefaultValue())
    GET_OR_DEFAULT(sig_path_prefix);
    GET_OR_DEFAULT(top_module);
    GET_OR_DEFAULT(top_instance);
    GET_OR_DEFAULT(netlist_path);
#undef GET_OR_DEFAULT
    opts.campaign_number = params.value(
        "campaign_number",
        std::stoi(absl::GetFlagReflectionHandle(FLAGS_campaign_number).DefaultValue())
    );
    opts.liberty_paths = params.value<std::vector<std::string>>("liberty_paths", {});

    FaultStrategy::Config config = params.get<FaultStrategy::Config>();
    opts.strategy = FaultStrategyFactory::buildFromJson(config, model);

    if (absl::GetFlag(FLAGS_fault_campaign_out)) {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from flag";
        opts.fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
    } else if (params.contains("fault_campaign_out")) {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from json";
        opts.fault_campaign_out = params["fault_campaign_out"].get<std::string>();
    } else {
        VLOG(2) << "GlobalOpts.fault_campaign_out set from default";
        if (opts.campaign_number == 1) {
            opts.fault_campaign_out = fault_campaign_out_file_defualt;
        } else {
            opts.fault_campaign_out = fault_campaign_out_directory_defualt;
        }
    }

    if (!absl::GetFlag(FLAGS_liberty_area_scale).empty()) {
        VLOG(2) << "GlobalOpts.liberty_area_scale set from flag";
        opts.liberty_area_scale = getLibertyAreaScale(absl::GetFlag(FLAGS_liberty_area_scale));
    } else if (params.contains("liberty_area_scale")) {
        VLOG(2) << "GlobalOpts.liberty_area_scale set from json";
        opts.liberty_area_scale =
            getLibertyAreaScale(params["liberty_area_scale"].get<std::string>());
    } else {
        opts.liberty_area_scale = default_liberty_area_scale;
    }
}

GlobalOpts GlobalOpts::parseCmdArgs(int argc, char** argv) {
    absl::ParseCommandLine(argc, argv);
    LogInitialize();

    std::string config_filepath = absl::GetFlag(FLAGS_config_file);
    if (config_filepath.empty()) {
        FaultStrategy::Config config = {
            absl::GetFlag(FLAGS_num_of_events).value_or(num_of_events_default),
            absl::GetFlag(FLAGS_seed).value_or(seed_default),
            parse_simulation_time(absl::GetFlag(FLAGS_simulation_time).value_or("")),
            clampThreadNumber(absl::GetFlag(FLAGS_thread_number).value_or(thread_number_default))
        };

        std::uint64_t campaign_number = absl::GetFlag(FLAGS_campaign_number);
        std::string fault_campaign_out;
        if (absl::GetFlag(FLAGS_fault_campaign_out)) {
            VLOG(2) << "GlobalOpts.fault_campaign_out set from flag";
            fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
        } else {
            VLOG(2) << "GlobalOpts.fault_campaign_out set from default";
            if (campaign_number == 1) {
                fault_campaign_out = fault_campaign_out_file_defualt;
            } else {
                fault_campaign_out = fault_campaign_out_directory_defualt;
            }
        }
        unit::AREA liberty_area_scale =
            getLibertyAreaScale(absl::GetFlag(FLAGS_liberty_area_scale));

        // TODO Check that all required flags were passed
        return {
            .sig_path_prefix = absl::GetFlag(FLAGS_sig_path_prefix),
            .top_module = absl::GetFlag(FLAGS_top_module),
            .top_instance = absl::GetFlag(FLAGS_top_instance),
            .netlist_path = absl::GetFlag(FLAGS_netlist_path),
            .fault_campaign_out = fault_campaign_out,
            .campaign_number = campaign_number,
            .strategy = FaultStrategyFactory::defaultStrategy(config),
            .liberty_paths = absl::GetFlag(FLAGS_liberty_paths),
            .liberty_area_scale = liberty_area_scale,
        };
    } else {
        try {
            std::ifstream config_file{config_filepath};
            SEE_PCHECK(config_file) << "Failed to open '" << config_filepath << "'";
            const auto config_json = nlohmann::json::parse(config_file);

            return config_json.get<GlobalOpts>();
        } catch (std::exception& error) {
            LOG(INFO) << "Json config parsing error: " << error.what() << "\n";
            SEE_CHECK(false) << "Ill formed config file '" << config_filepath << "'";
        }
    }
}
