// Copyright 2026 Antmicro <antmicro.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#include "VltConfigWriter.h"

#include "LogUtils.h"
#include "Signal.h"
#include "Utils.h"

#include <absl/strings/str_split.h>

#include <fstream>
#include <functional>
#include <optional>
#include <string_view>
#include <unordered_set>

namespace {

struct SignalElems {
    SignalType sig_type;
    static constexpr std::string_view mod = "*";
    std::string_view var;

    SignalElems(const Signal& signal) : sig_type(signal.type) {
        var = signal.cell.getPath();
        if (auto idx = var.find_last_of('.'); idx != var.npos) {
            // remove any prefix of the name (if exists)
            var = var.substr(idx + 1);
        }
        if (auto idxs = findNotEscapedBrackets(var)) {
            // remove any indices (if exist)
            var = var.substr(0, idxs->bopen_pos);
        }
    }

    bool operator==(const SignalElems& oth) const = default;
};

struct SignalElemsHash {
    std::size_t operator()(const SignalElems& value) const noexcept {
        const auto hash = std::hash<std::optional<std::string_view>>{};
        return hash(value.mod) ^ (hash(value.var) << 1);
    }
};

void writeHeader(std::ostream& os) {
    os << "// File generated by faultergeist\n\n";
    os << "`verilator_config\n";
    os << std::endl;
}

};  // namespace

void writeSignal(std::ostream& os, const SignalElems& signal) {
    switch (signal.sig_type) {
        case SignalType::REGISTER:
            os << "public_flat_rw -module \"" << signal.mod << "\" -var \"" << signal.var << "\"\n";
            break;
        case SignalType::WIRE:
            os << "forceable -module \"" << signal.mod << "\" -var \"" << signal.var << "\"\n";
            break;
        default:
            break;
    }
}

void VltConfigWriter::write(std::filesystem::path path, std::span<const Signal> signals) {
    VLOG(1) << "Writing public_flat config to: " << path.c_str();
    std::ofstream of(path);
    SEE_PCHECK(of) << "cannot open '" << path << "'. " << "Skipping public_flat config.";
    write(of, signals);
}

void VltConfigWriter::write(std::ostream& os, std::span<const Signal> signals) {
    std::unordered_set<SignalElems, SignalElemsHash> printed;

    writeHeader(os);
    for (const auto& sig : signals) {
        const auto signal = SignalElems(sig);
        if (!printed.contains(signal)) {
            printed.insert(signal);
            writeSignal(os, signal);
        }
    }
}
